services:
  - type: web
    name: cat-face-id-api
    env: python
    plan: free
    pythonVersion: 3.12.5
    buildCommand: |
      git lfs install
      git lfs pull
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
